pipeline {
    agent any 

    stages {
        stage('Paso 1: Preparar') {
            steps {
                bat 'npm install'
            }
        }
        stage('Paso 2: Probar') {
            steps {
                bat 'npx ng test --watch=false --browsers=ChromeHeadless'
            }
        }
    }

    post {
        always {
            junit 'test-results/*.xml'
        }
    }
}