pipeline {
    agent any 
    
    options {
        skipDefaultCheckout() 
    }

    stages {
        stage('Paso 1: Preparar') {
            steps {
                bat 'cd /d "C:\\DesarrolloWeb2\\ProyectoFac" && npm install'
            }
        }
        stage('Paso 2: Probar y Copiar') {
            steps {
                bat '''
                    cd /d "C:\\DesarrolloWeb2\\ProyectoFac"
                    
                    :: 1. Correr los tests
                    call npx ng test --watch=false --browsers=ChromeHeadless
                    
                    :: 2. Crear la carpeta destino en el workspace de Jenkins (Ruta absoluta)
                    if not exist "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\ProyectoAngular\\test-results" mkdir "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\ProyectoAngular\\test-results"
                    
                    :: 3. Copiar el XML usando la ruta completa de origen y destino
                    copy /Y "C:\\DesarrolloWeb2\\ProyectoFac\\test-results\\results.xml" "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\ProyectoAngular\\test-results\\results.xml"
                    
                    echo === VERIFICANDO COPIA ===
                    dir "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\ProyectoAngular\\test-results"
                '''
            }
        }
    }
    
    post {
        always {
            // Jenkins ahora sí lo verá porque está en su carpeta de trabajo
            junit 'test-results/results.xml'
        }
    }
}