on: [push] # Se activa cada vez que subas código



jobs:

  angular-test:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Instalar Node.js

        uses: actions/setup-node@v4

        with:

          node-version: '20'

      - name: Instalar dependencias

        run: npm install

      - name: Correr los tests

        run: npm test -- --watch=false --browsers=ChromeHeadless
